version: '3.8'

services:
  # ==========================================
  # 1. VERİTABANLARI (INFRASTRUCTURE)
  # ==========================================

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    command: --init-file /data/application/init.sql
    volumes:
      - ./mysql-init.sql:/data/application/init.sql
      - mysql_data:/var/lib/mysql

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: studentdb
    volumes:
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # ==========================================
  # 2. ALTYAPI SERVİSLERİ (INFRA)
  # ==========================================

  config-server:
    build: ./config-server
    ports:
      - "8888:8888"
    depends_on:
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=native

  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_APPLICATION_NAME=eureka-server

  api-gateway:
    build: ./api-gateway
    ports:
      - "8222:8222"
    depends_on:
      - eureka-server
    environment:
      - SPRING_APPLICATION_NAME=api-gateway
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  # ==========================================
  # 3. İŞ YAPAN MICROSERVISLER
  # ==========================================

  student-service:
    build: ./student-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/studentdb?charSet=UTF8
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=*
      - MANAGEMENT_HEALTH_CIRCUITBREAKERS_ENABLED=true
      - MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS=always

  course-service:
    build: ./course-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/coursedb?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  department-service:
    build: ./department-service
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/departmentdb?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888

  notification-service:
    build: ./notification-service
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
      - mongo
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/notificationdb
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  enrollment-service:
    build: ./enrollment-service
    ports:
      - "8085:8085"
    depends_on:
      - eureka-server
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/enrollmentdb?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  payment-service:
    build: ./payment-service
    ports:
      - "8087:8087"
    depends_on:
      - eureka-server
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/paymentdb
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  exam-service:
    build: ./exam-service
    ports:
      - "8086:8086"
    depends_on:
      - eureka-server
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/examdb?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  analytics-service:
    build: ./analytics-service
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  # ==========================================
  # 4. MONITORING
  # ==========================================
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  mysql_data:
  postgres_data:
  mongo_data: