spring.application.name=department-service
server.port=8083

# --- MySQL Data Source ---
# localhost:3306 yerine docker-compose'daki servis ad?n? (mysql) yaz?yoruz
spring.datasource.url=jdbc:mysql://mysql:3306/departmentdb?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- Eureka Discovery Client ---
# localhost:8761 yerine docker-compose'daki servis ad?n? (eureka-server) yaz?yoruz
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# --- Config Server ---
# localhost:8888 yerine docker-compose'daki servis ad?n? (config-server) yaz?yoruz
spring.config.import=optional:configserver:http://config-server:8888

# --- Actuator & Prometheus ---
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=department-service