# --- Service Port ---
server.port=8088
spring.application.name=analytics-service

# --- Eureka Discovery Client ---
# Using 'eureka-server' service name instead of localhost
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# --- Actuator and Prometheus ---
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=analytics-service